[package]
name = "ufmt-stdio"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
license = "BSL-1.0"
repository = "https://github.com/DoumanAsh/ufmt-stdio"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[dependencies]
ufmt = "0.1"
libc = "0.2"
